language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
install:
  - pip install -r requirements/test.txt
script:
  - coverage erase
  - coverage run test_apyclient.py --verbose
  - coverage report --show-missing
  - flake8 apyclient.py --max-line-length=120 --max-complexity=4
